### PR TITLE
Use this when you switch to 1.4

### PR DESCRIPTION
**Pull request by intangir**
some functions were renamed in 1.4 in the Entity.java class

this patches npclib to match

i couldnt get it to build but i tested a patch on combattag which did the same thing and it fixes the same error

### CODE REVIEW

**Comment by IDragonfire** [comment]
thank you very much,
but Majong change more, then these method ...
I hope the NPc Lib get updated:

https://github.com/Top-Cat/NPCLib

**Comment by intangir** [comment]
the other changes might not have effected the lib, did they?
i only saw the one crash

didnt notice any other internal bukkit function calls either, (could be some though)

**Comment by IDragonfire** [comment]
I have some compiler errors with bukkit 1.4 R0.1 ...

**Comment by intangir** [comment]
Is one of them related to that sline or line something include? I have a
fix for that

**Comment by intangir** [comment]
Ill share soon as I'm at my home pc

**Comment by intangir** [comment]
here it is:
https://github.com/mgrandi/Combat-Tag/commit/377a12325b090a8ceeb299c74897b2de33ac07d6

**Pull request merged**
